image: node:latest

cache:
  paths:
    - node_modules/

before_script:
    - npm install

pages:
    script:
        - npm run build
        - rm -rf public
        - mv dist public
    artifacts:
        paths:
            - public
    only:
        - master

